/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1alpha1 "datacenter-controller/pkg/apis/datacenter.pcl.ac.cn/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDataCenters implements DataCenterInterface
type FakeDataCenters struct {
	Fake *FakeDatacenterV1alpha1
}

var datacentersResource = schema.GroupVersionResource{Group: "datacenter.pcl.ac.cn", Version: "v1alpha1", Resource: "datacenters"}

var datacentersKind = schema.GroupVersionKind{Group: "datacenter.pcl.ac.cn", Version: "v1alpha1", Kind: "DataCenter"}

// Get takes name of the dataCenter, and returns the corresponding dataCenter object, and an error if there is any.
func (c *FakeDataCenters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(datacentersResource, name), &v1alpha1.DataCenter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataCenter), err
}

// List takes label and field selectors, and returns the list of DataCenters that match those selectors.
func (c *FakeDataCenters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataCenterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(datacentersResource, datacentersKind, opts), &v1alpha1.DataCenterList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataCenterList{ListMeta: obj.(*v1alpha1.DataCenterList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataCenterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataCenters.
func (c *FakeDataCenters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(datacentersResource, opts))
}

// Create takes the representation of a dataCenter and creates it.  Returns the server's representation of the dataCenter, and an error, if there is any.
func (c *FakeDataCenters) Create(ctx context.Context, dataCenter *v1alpha1.DataCenter, opts v1.CreateOptions) (result *v1alpha1.DataCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(datacentersResource, dataCenter), &v1alpha1.DataCenter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataCenter), err
}

// Update takes the representation of a dataCenter and updates it. Returns the server's representation of the dataCenter, and an error, if there is any.
func (c *FakeDataCenters) Update(ctx context.Context, dataCenter *v1alpha1.DataCenter, opts v1.UpdateOptions) (result *v1alpha1.DataCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(datacentersResource, dataCenter), &v1alpha1.DataCenter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataCenter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataCenters) UpdateStatus(ctx context.Context, dataCenter *v1alpha1.DataCenter, opts v1.UpdateOptions) (*v1alpha1.DataCenter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(datacentersResource, "status", dataCenter), &v1alpha1.DataCenter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataCenter), err
}

// Delete takes name of the dataCenter and deletes it. Returns an error if one occurs.
func (c *FakeDataCenters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(datacentersResource, name, opts), &v1alpha1.DataCenter{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataCenters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(datacentersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataCenterList{})
	return err
}

// Patch applies the patch and returns the patched dataCenter.
func (c *FakeDataCenters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataCenter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(datacentersResource, name, pt, data, subresources...), &v1alpha1.DataCenter{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataCenter), err
}
